### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by ferki** [RexOps/rexify-website#106]
On one hand, it would be nice to replace the current syntax highlighting based on highlight.js with Statocles' built-in highlighter plugin, if we can make that work.

On the other hand (and perhaps until the above replacement is being evaluated), we could also update highlight.js to a recent version, preferably one which only supports the languages we actually need to highlight on the rexify site (I guess Perl+Bash+YAML, not sure if anything else is presented as code which needs highlighting).

Todos:
- [x] upgrade highlight.js to latest version
- [x] optimize highlight.js to contain only languages which are actually necessary
- [x] replace highlight.js

**Comment by ehuelsmann** [comment]
Quoting @ferki: 

ehuelsmann: hi! I've played with the statocles highlight plugin, and I got it working
I've pushed some WIP code to wip-highlight branch
we could remove a lot more code again, but I don't like the plugin overall
1. it would make writing the content in markdown feel unnatural to mix in the correct highlighting hint around code blocks
2. it is sensitive to leading whitespace inside the begin/end block
3. we would still need to escape template code inside highlight blocks
I think those could be only avoided by replacing the markdown renderer (e.g. to something that supports github flavored markdown and/or fenced code blocks with language hinting) and/or modifying the highlighting plugin

**Comment by ferki** [comment]
@ehuelsmann: oh, yeah, I guess I could have commented here instead of IRC :)

So the todos for this topic still seems the same: upgrade/finetune highlight.js until we can replace it with a static highlighter. I'll add tickboxes for these two in the OP.

**Comment by ferki** [comment]
Fixed on #122. Now there's a Statocles plugin handling the highlighting during site build time, instead of highlight.js during browsing time.
