### ISSUE TITLE
Document feature flags in Rex's POD

### ISSUE THREAD

**Issue by ehuelsmann** [RexOps/rexify-website#119]
The goal here is to complete Rex's documentation and refer from the website to that document, eliminating the need for content/guide/feature_flags.md

**Comment by ferki** [comment]
Well, there's certainly a todo about it in the website repo (remove page/redirect link), but I feel like it's much more of an issue for the [RexOps/Rex](https://github.com/RexOps/Rex) repo, so I think I might transfer it to there later.

**Comment by ferki** [comment]
This was solved on in the RexOps/Rex#1389, and subsequently here on 6867bbf5863cb2f43b0b7d524e631c08cef2934f. 

[Feature flags](https://metacpan.org/pod/Rex#FEATURE-FLAGS) are now documented as part of Rex.
