### ISSUE TITLE
Example code in FAQ doesn't work

### ISSUE THREAD

**Issue by randyl** [RexOps/rexify-website#152]
In the file `content/docs/faq/index.md`, the question "How can I run a block of code with one command?" has this example code:

```$ rexify --use Rex::Misc::ShellBlock```

That command no longer works. There's a ticket for it at https://github.com/RexOps/Rex/issues/1201. I would submit a pull request to fix this answer, but I'm not sure what the example code should be changed to.

**Comment by ferki** [comment]
@randyl: thanks for the report! I'm going to update that FAQ item to don't include that instruction.
