### ISSUE TITLE
Social media sites are unable to find Rex's logo

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [RexOps/rexify-website#20]
When I paste link to Rex's website on twitter, linkedin of facebook, they won't display nice logo of project but picture with "Linux Tag" or "Fork me on GitHub" instead.

**Comment by ehuelsmann** [comment]
Just tested and seeing the same with [Riot](https://riot.im/)'s "link preview" feature. This may be caused by the fact that the logo in the upper right corner is in fact a background image.

**Comment by ferki** [comment]
I found the page about [The Open Graph protocol](http://ogp.me/) to be helpful to understand what needs to be implemented here (basically adding more meta tags).
