### ISSUE TITLE
website doesn't work on mobile Webkit browsers

### ISSUE THREAD

**Issue by Nowaker** [RexOps/rexify-website#26]
I get "aw snap" both on Chrome and Opera, which means all mobile Webkit browsers are probably affected. Only Firefox work OK on my mobile (Android 4.2).

**Comment by ehuelsmann** [comment]
I'm not seeing this issue on Chrome today (Android 6.0).

**Comment by ehuelsmann** [comment]
Just downloaded and installed Opera Mini. No issues either. Closing as "no longer problematic".
