### ISSUE TITLE
No link to result

### ISSUE THREAD

**Issue by szabgab** [RexOps/rexify-website#28]
I just searched for http://www.rexify.org/search?q=timeout the resulting page told me there is something related in the API, but did not provide any link to read more about it. (and I really wanted to see if and how I might be able to set a short timeout for some of the commands)

```
Found here:
) Set the password for the sudo command. timeout($seconds) Set the timeout for the ssh
```

**Comment by krimdomu** [comment]
Hi @szabgab 
thanks for the issue. This is also solved for a while now because we changed the content engine a while ago.
