### ISSUE TITLE
add sudo + tty FAQ entry

### ISSUE THREAD

**Issue by ferki** [RexOps/rexify-website#37]
Sometimes rex users get a `sudo: sorry, you must have a tty to run sudo` error, e.g. as [described here](https://groups.google.com/forum/#!searchin/rex-users/tty/rex-users/8RpJaTeApUs/K-Pj5pKsiCMJ). It might worth adding this case to the FAQ.

**Comment by ehuelsmann** [comment]
PR submitted to Rex itself for inclusion in the base documentation; no need for a FAQ entry in that case.
