### ISSUE TITLE
Rex in a (vagrant) box

### ISSUE THREAD

**Issue by bechtoldt** [RexOps/rexify-website#41]
Is there an existing vagrant box/ Vagrantfile that can be used with rex? I couldn't find anything about that on rexify.org (besides rex-box).

If not I could try to add Rex support to https://github.com/bechtoldt/vagrant-devenv / https://github.com/bechtoldt/iac-vagrant.

**Comment by krimdomu** [comment]
Hi,
are you looking for a Vagrantfile that just setup rex inside a vagrant box, or are you looking for a Vagrant provisioner binding/module for rex?

For the later one i have seen this in the past: https://github.com/rfox90/vagrant-rex but i don't know how good it works.

**Comment by bechtoldt** [comment]
I've resolved it myself.

https://github.com/bechtoldt/iac-vagrant / https://github.com/bechtoldt/vagrant-assets/blob/master/scripts/provision/debian/custom/rex_install_git/A_base.sh

Sorry for the noise. :)

**Comment by ferki** [comment]
@bechtoldt: ah, we didn't have that, thanks for your work on it!

ps.: I understand the differences of the scopes, just wanted to mention that the Rex::Box stuff you found earlier is actually a Vagrant-like functionality implemented with Rex ^^
