### ISSUE TITLE
Use markdown in more places

### ISSUE THREAD

**Issue by ferki** [RexOps/rexify-website#45]
I think it would make sense to use markdown in more places to ease authoring of new content, especially for the book :)

It might also be an option to reuse some existing content management system for it, but I think we can also just convert markdown into HTML internally.

**Comment by krimdomu** [comment]
i also thought of using a content management system... but the question is which we want to use. The best would be if it already integrates a good search...

**Comment by krimdomu** [comment]
it would be also good, if this cms supports multi language content...

**Comment by ehuelsmann** [comment]
We seem to have settled on using Statocles, at least for now. When that turns out not to work, lets open an issue again.
