### ISSUE TITLE
Clarify requirements on 'Managed Hosts'

### ISSUE THREAD

**Issue by szabgab** [RexOps/rexify-website#48]
http://www.rexify.org/docs/guides/start_using__r__ex.html  Under 'Managed Hosts'
there is a sentence that I think could be improved

"Rex doesn't try use any non-core Perl modules on the remote hosts, but some operating systems (e.g. RHEL/CentOS 7, Fedora 21) might not supply them out of the box. In this case you might need to install them first (currently this means the Digest::MD5 module)."

I think it would be better:

"Rex only uses core Perl modules on the remote hosts, but some operating systems (e.g. RHEL/CentOS 7, Fedora 21) might not supply all of them out of the box. In this case you might need to install them first (currently this means the Digest::MD5 module)."

And then IMHO, the "install" should be a link to another page, or it should open some hidden text, that explains how to install those modules on the OS-es where they are missing.

**Comment by krimdomu** [comment]
Hi @szabgab ,
this is a good idea. Thanks. I'm going to add this, too.

**Comment by ferki** [comment]
Yup, that's better wording, thanks! :)

I believe Rex should handle this situation transparently to the end user, and I just wanted to put up the warning until then. We can of course create, and publish helper page too, but I think that's about the same amount of work as providing a fallback within Rex to e.g. `md5sum` in the known cases (or letting rex install the module on the remote after opting-in with a feature flag to allow it).

**Comment by krimdomu** [comment]
Content is now changed.
Thanks.

@ferki yes, we can think about such an option. i think this would be good. For pure perl modules we can also think of uploading the missing one to the remote host somewhere under /var/cache/rex.
