### ISSUE TITLE
How to get support ?

### ISSUE THREAD

**Issue by szabgab** [RexOps/rexify-website#49]
http://www.rexify.org/support.html under 'Community Support' tells us to join the 'user group' , but I don't know what does that mean. Could the 'user group' be turned into a link to https://groups.google.com/forum/#!forum/rex-users if that's what you mean. (just as I later found on the left hand side of the page)

IMHO it would be also nice to link to http://stackoverflow.com/questions/tagged/rex from both the 'Community Support' entry and from the bottom left side and then monitor that tag on StackOverflow. 
(Though I am not sure if it would not be better to have it on http://serverfault.com/ )

**Comment by krimdomu** [comment]
@szabgab 
same for this one :+1: 
i think the better page is really serverfault because it is more an admin thing

**Comment by szabgab** [comment]
As I understand you can ask moderators to move the questions: http://meta.stackexchange.com/questions/157231/how-do-i-move-an-existing-question-i-wrote-from-stack-overflow-to-server-fault

**Comment by ferki** [comment]
@szabgab: do you know of a nice solution of handling all those "communication interfaces" in a single place? I mean we have:
- github issues
- IRC channel
- google group
- twitter account
- we announce stuff on google plus
- have disqus integrated for comments on the website,
- someone posted on reddit and linkedin
- serverfault/stackoverflow is coming up
- what not

Maybe it's OK to coordinate all those via email, but maybe it's time to think about communication strategy a bit :)

**Comment by krimdomu** [comment]
links are now added (needs sometime to gets displayed, because of cloudfront)
