### ISSUE TITLE
Link to Perl tutorial

### ISSUE THREAD

**Issue by szabgab** [RexOps/rexify-website#50]
It would be nice if this page: http://www.rexify.org/docs/guides/just_enough_perl_for_rex.html could link to the Perl Tutorial at http://perlmaven.com/perl-tutorial

**Comment by krimdomu** [comment]
Hi @szabgab 

this is a good idea. I'm going to add this.

**Comment by ferki** [comment]
:+1:

**Comment by krimdomu** [comment]
Link is added.

**Comment by szabgab** [comment]
thank you!
