### ISSUE TITLE
Missing path for installing Rex in Fedora 22 & 23

### ISSUE THREAD

**Issue by pablrod** [RexOps/rexify-website#52]
Repo file in [Get Rex](http://www.rexify.org/get.html#tab5) uses $releasever but the path for the last releases is missing.
I use Rex without problems in Fedora 22 & 23, but replacing $releasever to 21.

Please add the folders 22/ & 23/ to https://rex.linux-files.org/Fedora/ (Maybe a symbolic link to 21/ folder)

**Comment by ferki** [comment]
Fedora ships official Rex since a good while and we also don't maintain OS packages on our own anymore, so I'm closing this.

Sorry for the late response, but thanks for the report anyway!
