### ISSUE TITLE
CentOS install instructions referring to Fedora

### ISSUE THREAD

**Issue by ferki** [RexOps/rexify-website#53]
http://www.rexify.org/get.html#tab3

**Comment by krimdomu** [comment]
which webbrowser are you using? because on my firefox it shows the right content

**Comment by ferki** [comment]
I checked in firefox too, but it's the same for me
![2015-11-22-130023_1380x930_scrot](https://cloud.githubusercontent.com/assets/3117609/11323677/0628d0f6-9119-11e5-98d7-f3f23543bbb2.png)

see also RexOps/Rex#806
