### ISSUE TITLE
search lists all API version

### ISSUE THREAD

**Issue by ferki** [RexOps/rexify-website#57]
When a search is executed, API results are listed twice, once for each API version:

```
Commands.pm (API version 1.3)
[...]
Commands.pm (API version 1.4)
[...]
```

I expect it would quickly get confusing as we release more versions, so I guess it would be nice/enough to only list the latest API version in search results.

The API version can be changed later on the linked page if needed.

**Comment by ehuelsmann** [comment]
API searching has now been deferred to MetaCPAN. This issue is no longer relevant.
