### ISSUE TITLE
Loop template example doesnt work?

### ISSUE THREAD

**Issue by djzort** [RexOps/rexify-website#65]
On this page: https://www.rexify.org/docs/guides/using_modules_and_templates.html

The example starting with: `for my $server (@{ $ntp_servers }) {`

Doesnt seem to work, perhaps I am missing something?

**Comment by ehuelsmann** [comment]
I'm sorry, but in order to report a problem, could you please indicate which steps you went through to create the situation you tested, what was the actual result and what is the expected result?

**Comment by ferki** [comment]
I've tested the example both with local and remote execution, and it created the file with the expected contents. Unfortunately there aren't any other clue apart from "Doesnt seem to work", so I don't think we can do anything else on this issue in its current state.

@djzort: I'd be happy to look into this further, so if you still have problems with running the example, please reopen this issue and include more context (like error messages, rex version, remote/local run, etc.).
