### ISSUE TITLE
Tag questions on Server Fault

### ISSUE THREAD

**Issue by elisdg** [RexOps/rexify-website#66]
There are some questiong at serverfault.
If someone with sufficient reputation (I think >300) could edit these questions and tag them with "rex", the link on the website wouldn't address an empty space :)
thank you

https://serverfault.com/questions/894597/how-to-create-a-directory-with-rex
https://serverfault.com/questions/913558/passwordless-ssh-local-port-forwarding
https://serverfault.com/questions/923386/how-to-distribure-sudoers-files-with-rex-configuration-management
https://serverfault.com/questions/922862/how-to-backup-a-file-before-changing-it-with-rex-configuration-management-rex

**Comment by ferki** [comment]
Thanks for the issue! I've reworded the title to make the required action more clear, and tagged it as "help wanted", hoping that someone with sufficient reputation finds this and tags the questions.

**Comment by elisdg** [comment]
the tag [rex] is created now and I tagged the relevant questions (all the above and all that I found) but question-editing has to wait for the authors or moderators approval.
