### ISSUE TITLE
Migrate website to GitHub pages

### ISSUE THREAD

**Issue by ferki** [RexOps/rexify-website#67]
The website is the primary point for both new and existing Rex users to learn about the project, and to keep themselves up-to-date. It helps a lot if both the infrastructure and content of the website are simple and easy to maintain and edit.

Using GitHub pages for the website would help maintenance considerably:
 - plain git can be used to manage information/document lifecycle, simplifying both maintenance and
 - less worries about expiring certificates (also how to renew one, or who can renew it)
 - deployment is already automated
 - less worries about handling traffic spikes
 - can remove CDN from current setup (simplifies the project, and saves cost)
 - [add your own points here]

**Comment by ehuelsmann** [comment]
Depends on #68

**Comment by ferki** [comment]
The website is now being served via GitHub pages. Thanks for everyone involved!
