### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by LeMerP** [RexOps/rexify-website#73]
On get.rexify.org

**Comment by ehuelsmann** [comment]
@ferki , @krimdomu : this is still going on. Is there anything I can do to help resolve this?

**Comment by ferki** [comment]
@LeMerP: thanks for the report, and sorry about that. On brighter news, we're working on improving the web presence of all things around rex.

@krimdomu @ehuelsmann: personally, I would propose to retire `get.rexify.org`. Or alternatively, redirect all requests for `get.rexify.org` to `https://www.rexify.org/get/index.html` to show installation instructions, but that feels a bit like breaking existing scripts in an even worse way.

I would argue we should not endorse `curl`ing web content and then piping that into a perl process to execute, and especially not with `--sudo` involved. Also, the fatpacked App::cpanminus on `get.rexify.org` is only at version 1.7024, which is from 2015-01-12, so seems unmaintained.

**Comment by ehuelsmann** [comment]
@ferki Yes, I think retiring is best; possibly with a deprecation period where the site gets redirected for a few months to the URL you propose. Then bots get the chance to update their crawling tables.

**Comment by ferki** [comment]
`get.rexify.org` doesn't exist anymore. Closing this issue.

"So long, and thanks for all the fish!" :)
