### ISSUE TITLE
Add support for timestamped content

### ISSUE THREAD

**Issue by ehuelsmann** [RexOps/rexify-website#87]
So we can use that to port over the old news to Statocles

**Comment by ehuelsmann** [comment]
A few things to add to the news history:

* Migration to statocles
* Communication of the decision to move api docs and search to MetaCPAN
* Communication of the decision to move distribution of Rex modules to CPAN
* Communication of the decision to move the responsibility of package development to packagers

**Comment by ferki** [comment]
Blog is deployed now via #95. About the content-to-be-written: the last two points from above already got their own issues, perhaps we can create one more issue to cover the website migration story.

But overall I consider this issue solved.
